apiVersion: v1
kind: Pod
metadata:
  labels:
    run: healthy-pod
  name: healthy-pod
spec:
  containers:
  - image: nginx
    name: healthy-pod
    resources: {}
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
