apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-pod
  name: app-pod
spec:
  serviceAccountName: app-sa #link service account here
  containers:
  - image: nginx
    name: app-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
