apiVersion: v1
kind: Pod
metadata:
  name: log-collector
  namespace: monitoring
spec:
  containers:
  - name: log-collector
    image: busybox
    command:
    - sleep
    - "3600"
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 10Mi
