apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: storage
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/data-pv
