apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: default
spec:
  volumes:
  - name: work-dir
    emptyDir: {}
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
      - name: work-dir
        mountPath: /work
  initContainers:
    - name: init-setup
      image: busybox
      command: ['sh', '-c', 'echo "setup complete" > /work/setup.txt']
      volumeMounts:
      - name: work-dir
        mountPath: /work
