apiVersion: v1
kind: Pod
metadata:
  name: data-pod
  namespace: storage
spec:
  containers:
    - name: data-pod
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/data
        name: data-storage
  volumes:
    - name: data-storage
      persistentVolumeClaim:
        claimName: data-pvc
