apiVersion: v1
kind: Pod
metadata:
  labels:
    run: crasher
  name: crasher
spec:
  containers:
  - image: busybox
    name: crasher
    command:
      - "sleep"
      - "3600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
