apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secrets-pod
  name: secrets-pod
spec:
  containers:
  - image: nginx
    name: secrets-pod
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
