apiVersion: v1
kind: Pod
metadata:
  name: affinity-test-pod
  namespace: exam
spec:
  containers:
  - name: affinity-test-pod
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
            - nvme
