apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api
  name: api
  namespace: microservices
spec:
  containers:
  - image: nginx:alpine
    name: api
    resources: {}
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: host
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
