apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam-pv
spec:
  capacity: #C
    storage: 1Gi
  accessModes: #A
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #R
  storageClassName: exam-sc
  hostPath: #H
    path: /mnt/examdata
