apiVersion: v1
kind: Pod
metadata:
  labels:
    run: exam-cache-pod
  name: exam-cache-pod
  namespace: exam
spec:
  containers:
  - image: nginx:1.25
    name: exam-cache-pod
    env:
    - name: CACHE_TOKEN
      valueFrom:
        secretKeyRef:
          name: exam-cache-secret
          key: cache_token
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
