apiVersion: v1
kind: Pod
metadata:
  labels:
    run: exam-net-secure-pod
  name: exam-net-secure-pod
  namespace: exam
spec:
  containers:
  - image: nginx:1.25
    name: exam-net-secure-pod
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: exam-net-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
