apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: logging
spec:
  containers:
  - name: log-writer
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) hello from log-writer; sleep 2; done"]
  - name: log-reader
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) hello from log-reader; sleep 2; done"]
