apiVersion: batch/v1
kind: CronJob
metadata:
  name: mock-cron
  namespace: mock
spec:
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: mock-cron
            resources: {}
            command:
            - echo
            - hello
          restartPolicy: OnFailure
status: {}
