apiVersion: v1
kind: PersistentVolume
metadata:
  name: mock-pv
spec:
  capacity: #C
    storage: 500Mi
  accessModes: #A
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #R
  storageClassName: mock-sc
  hostPath: #H
    path: /mnt/mockdata
