apiVersion: v1
kind: Pod
metadata:
  name: mock-multi
  namespace: mock
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "while true; do echo hello from writer; sleep 2; done"]
  - name: reader
    image: busybox
    command: ["sh", "-c", "while true; do echo hello from reader; sleep 2; done"]
