apiVersion: v1
kind: Pod
metadata:
  name: mock-db-pod
  namespace: mock
spec:
  containers:
  - name: mock-db-container
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mock-db-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: mock-db-secret
          key: password
