apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-pod-1
  name: mock-pod-1
  namespace: mock
spec:
  containers:
  - image: nginx
    name: mock-pod-1
    resources:
      requests:
        cpu: 100m
      limits:
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
