apiVersion: v1
kind: Pod
metadata:
  name: mock-app-pod
  namespace: mock
spec:
  containers:
  - name: mock-app-container
    image: nginx
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: mock-app-config
          key: log_level
