apiVersion: batch/v1
kind: Job
metadata:
  name: data-processor
spec:
  completions: 1
  backoffLimit: 3
  template:
    spec:
      containers:
      - image: busybox
        name: data-processor
        command: ["echo", "done"]
      restartPolicy: Never
