apiVersion: batch/v1
kind: Job
metadata:
  name: exam-job
  namespace: exam
spec:
  completions: 1
  backoffLimit: 3
  template:
    metadata: {}
    spec:
      containers:
      - image: busybox
        name: exam-job
        resources: {}
      restartPolicy: Never
status: {}
