apiVersion: batch/v1
kind: Job
metadata:
  name: log-writer
  namespace: batch-ops
spec:
  completions: 3
  backoffLimit: 2
  template:
    metadata: {}
    spec:
      containers:
      - image: busybox
        name: log-writer-container
        command: ["echo", "processing", "complete"]
      restartPolicy: Never
status: {}
