apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exam-pvc
  namespace: exam
spec:
  storageClassName: exam-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
