apiVersion: v1
kind: Pod
metadata:
  labels:
    run: exam-storage-pod
  name: exam-storage-pod
  namespace: exam
spec:
  containers:
  - image: nginx
    volumeMounts:
    - mountPath: /data
      name: exam-storage-vol
    name: exam-storage-container
  volumes:
    - name: exam-storage-vol
      persistentVolumeClaim:
        claimName: exam-pvc
