apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-backend-svc
  name: web-backend-svc
  namespace: web-zone
spec:
  ports:
  - name: open-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-backend
  type: ClusterIP
status:
  loadBalancer: {}
