apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probe-test-pod
  name: probe-test-pod
  namespace: exam
spec:
  containers:
    - image: nginx
      name: pod
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
