apiVersion: v1
data:
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-04-07T05:41:09Z"
  name: my-secret
  namespace: default
  resourceVersion: "70734"
  uid: 73b45a16-70b5-4440-95d8-1039688cd5e0
type: Opaque
