apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-demo
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spread-demo
  template:
    metadata:
      labels:
        app: spread-demo
    spec:
      containers:
      - name: spread-demo
        image: nginx
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spread-demo
            topologyKey: kubernetes.io/hostname
